config/routes.rb
Bullcentury::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/:locale' => 'home#index'

  scope '(:locale)', locale: /ru|ua|en|hu/ do
    root  to: 'home#index'
    get 'how_it_works', :to => 'home#how_it_works'
    get 'quick_start', :to => 'home#quick_start'
    get 'university', :to => 'home#university'
    get 'faq', :to => 'home#faq'
    get 'rules', :to => 'home#rules'
    get 'company', :to => 'home#company', :as =>  :company
    get 'mentors', :to => 'home#mentors'
    match '/feedbacks',     to: 'feedbacks#new', via: 'get'
    resources "feedbacks", only: [:new, :create]

    get 'receive_money', to: 'profiles#receive_money', as: 'receive_money'
    get 'receive_money_success', to: 'profiles#receive_money_success', as: 'receive_money_success' #temp
    get 'invest_project', to: 'profiles#invest_project', as: 'invest_project'
    get 'refunds', to: 'profiles#refunds', as: 'refunds'
    get 'activities_report', to: 'profiles#activities_report', as: 'activities_report'
    get 'my_project', to: 'profiles#my_project', as: 'my_project'
    get 'promote_project', to: 'profiles#promote_project', as: 'promote_project'
    get 'shipping', to: 'profiles#shipping', as: 'shipping'
    get 'profile_management', to: 'profiles#profile_management', as: 'profile_management'
    get 'update_cities', to: 'profiles#update_cities', as: 'update_cities'
    get 'receive_money_part2', to: 'profiles#receive_money_part2', as: 'receive_money_part2'

    get 'success', to: 'profiles#success'
    
    get  'dashboard', to: 'profiles#dashboard', as: 'dashboard'
    get  'profiles/:id', :to => 'profiles#show', :as =>  :profile
    get  'profiles/:id/edit', :to => 'profiles#edit', :as =>  :edit_profile
    post 'profiles/update', :to => 'profiles#update'
    get 'categories/:key', :to => 'categories#show', :as => :category

    resources :pledge_transactions
    resources :projects do
      resources :rewards
      resources :authors

      member do
       get 'publish'
       get 'stop'
       get 'agreement_page'
     end
      collection do
        get 'leisure'
        get 'media'
        get 'art'
        get 'crazy'
        get 'innovation'
        get 'social'
      end
    end
    namespace :api, defauts: {format: :json} do
      resources :projects, only: [:index, :show, :update] do
        resources :rewards, only: [:index, :show, :update, :create, :destroy]
      end
      resources :currencies, only: [:index]
      resources :categories, only: [:index]
      resources :cities, only: [:show, :index]
      resources :countries, only: [:index]
      resources :profiles, only: [:show, :update]
    end

  end

  devise_for :users, :controllers => {  confirmations: 'confirmations', :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController
  skip_before_filter :verify_authenticity_token  
  def index
    render json: projects
  end

  def show
    render json: project
  end

  # def create
  #   project = projects.create!(product_params)
  #   render json: project
  # end

  # def update
  #   @product = Product.find(params[:id])
  #   if @product.update_attributes(product_params)
  #     redirect_to @product
  #   else
  #     render :index
  #   end
  # end

  def update
    puts 'UPDATE START'
    params[:project] = convert_data_uri_to_upload(params[:project])
    puts 'params[:project][:image]'
    puts params[:project][:image]
    puts 'UPDATE END'

    project.update_attributes(project_params)
    render nothing: true
  end

  #def delete
  #  render json: product
  #end

  # def destroy
  #    project.destroy
  #    render nothing: true
  # end

  # def new
  #   @product = Product.new
  #   @categories = Category.all
  # end

  # def create
  #   @product = Product.new(product_params)
  #   if @product.save
  #     redirect_to products_path
  #   end
  # end

  # def edit
  #   @product = Product.find(params[:id])
  #   @categories = Category.all
  # end


  



  # def destroy
  #   Product.find(params[:id]).destroy
  #   redirect_to products_path
  # end

  private

  def project
  	@project ||= Project.find(params[:id])
  end

  def projects
  	@projects ||= Project.all  
  end

  

  def project_params
    params.require(:project).permit(
      :name, 
      :description, 
      :tweet, 
      :funding_duration_in_days, 
      :funding_goal, 
      :image, 
      :remote_image_url, 
      :video, 
      :currency_id, 
      :creator_biography, 
      :website, 
      :timeline1, 
      :timeline2, 
      :timeline3, 
      :timeline_date1, 
      :timeline_date2, 
      :timeline_date3,
      :country_id, 
      :city_id,
      :region, 
      :zip, 
      :address,
      :category_ids => []
    )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :except => [:new, :show, :index, :leisure, :media, :art, :crazy, :innovation, :social, :create]

  def new
    @project = Project.new
    @currencies = Currency.all
  end

  def create
    @project = Project.new(project_params)
    if user_signed_in?
      @project.user_id = current_user.id
      if @project.save
        category_ids = [params[:project][:category]] || []
        category_ids.each do |category_id|
          categorization = Categorization.new({:category_id => category_id, :project_id => @project.id})
          categorization.save
        end
        if !current_user.current_project_id
          current_user.current_project_id = @project.id
          current_user.save
        end
        redirect_to edit_project_url(@project.id)
      else
        render 'new'
      end
    # user are not signed in
    else
      #@project.user_id = current_user.id
      if @project.save
        category_ids = [params[:project][:category]] || []
        category_ids.each do |category_id|
          categorization = Categorization.new({:category_id => category_id, :project_id => @project.id})
          categorization.save
        end
        #Присвоить какой-то номер мол в очереди в session и в бд
        # после регистрации на edit c предзаполненными. данными
        session[:new_project_id] = @project.id
        @project.quick = true
        @project.save
        #if !current_user.current_project_id
        #  current_user.current_project_id = @project.id
        #  current_user.save
        #end
        puts "GO GO GO "
        redirect_to new_user_session_path #login/regictrstion
      else
        render 'new'
      end
    end
  end

  def show
    @project = Project.find(params[:id])
    # if @project.can_read? current_user.try(:id)
    if @project.is_published? || @project.is_owner?(current_user.try(:id))
      @project = Project.find(params[:id])

      @pledgedAmount = @project.calc_pledged
      @pledged = @project.calc_pledged_percentage @pledgedAmount
      @new_pledge = PledgeTransaction.new()
    else
      render :file => "#{Rails.root}/public/404.html", :status => :not_found
    end
  end

  def index
    @projects = Project.where(state: 'set_for_publish')
  end

  def edit
    @currencies = Currency.all
    @project = Project.find(params[:id])
    if session[:new_project_id] && (session[:new_project_id].to_i == params[:id].to_i)
      session.delete(:new_project_id)
      @project.user_id = current_user.id
      current_user.current_project_id = @project.id
      current_user.save
      @project.quick = false
      @project.save
    end

    if can?( :manage, @project) and @project.state == "created"
      @project = Project.find(params[:id])
    else
      session[:errors] = "This project can't be modified"
      redirect_to @project
    end
  end

  def update
    @project = Project.find(params[:id])
    puts 'IF START UPDATE'
    if can?( :manage, @project) and @project.state == "created"
      puts 'IF CAN'
      @project = Project.find(params[:id])
      begin
        if @project.update(project_params)
          puts 'IF UPDATE'
          # @project.update_categories params[:project][:category_ids]
          # redirect_to @project
          render 'edit'
        else
          render 'edit'
        end
      rescue ActiveRecord::StatementInvalid => ex
        session[:errors] = "Tweet is to long"
        redirect_to edit_project_path(@project)
      end
    else
      session[:errors] = "This project can't be modified"
      redirect_to @project
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  def publish
    @project = Project.find(params[:id])
    if @project.user_id == current_user.id
      if @project.set_for_publish
        flash[:notice] = "Project has transferred for a review."
        render :show
      else
        session[:errors] = @project.get_validation_errors.values.compact.join('<br/>').html_safe
        begin
          redirect_to :back
        rescue ActionController::RedirectBackError
          render :show
        end
      end
    else
      session[:errors] = "You have no rights to do that."
      begin
        redirect_to :back
      rescue ActionController::RedirectBackError
        redirect_to @project
      end
    end
  end


  def agreement_page
    @project = Project.find(params[:id])
    if @project.user_id == current_user.id
      unless @project.valid_for_publish?
        session[:errors] = @project.get_validation_errors.values.compact.join('<br/>').html_safe
        render :show
      else
        render
      end
    else
      session[:errors] = "You have no rights to do that."
      begin
        redirect_to :back
      rescue ActionController::RedirectBackError
        redirect_to @project
      end
    end
  end

  def popular
    @popular_projects = Project.where(state: 'set_for_publish')
    @popular_projects = Array.new unless @popular_projects
  end

  def successful
    @successful_projects = Project.where(state: 'set_for_publish')
    @successful_projects = Array.new unless @successful_projects
  end

  def leisure
    @category = :leisure
    @projects = Category.find_by_key(@category).projects
    render :action => 'index'
  end

  def media
    @category = :media
    @projects = Category.find_by_key(:media).projects
    render :action => 'index'
  end

  def art
    @category = :art
    @projects = Category.find_by_key(:art).projects
    puts 'TEST   '
    puts @projects
    render :action => 'index'
  end

  def crazy
    @category = :crazy
    @projects = Category.find_by_key(:crazy).projects
    render :action => 'index'
  end

  def innovation
    @category = :innovation
    @projects = Category.find_by_key(:innovation).projects
    render :action => 'index'
  end

  def social
    @category = :social
    @projects = Category.find_by_key(:social_projects).projects
    render :action => 'index'
  end

  private
    def project_params
      #console.log(params) 
      puts params.inspect
      params.require(:project).permit(
        :name, 
        :description, 
        :tweet, 
        :funding_duration_in_days, 
        :funding_goal, 
        :image, 
        :remote_image_url, 
        :video, 
        :currency_id, 
        :creator_biography, 
        :website, 
        :timeline1, 
        :timeline2, 
        :timeline3, 
        :timeline_date1, 
        :timeline_date2, 
        :timeline_date3,
        :country_id, 
        :city_id,
        :region, 
        :zip, 
        :address
      )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit/_author.html.haml
.row
  .col-sm-5.col-md-5
    %form{:name => 'projectAuthorForm', 'ng-submit' => 'saveAuthor()'}
      - if  @project.author
      - elsif can?( :manage, @project.author)
        .alert.alert-warning
          = t('provide_author_info')
          = link_to t('edit_author'), edit_profile_path(@project.author), :class => 'b-project__fill-author-info-btn btn btn-info'
      .row.disable-input-style
        .col-sm-5.no_right_padding
          / %a{:href=>'javascript:;', :class=>'thumbnail fixed-size-150'}
          /   - if @project.author and @project.author.image?
          /     = image_tag @project.author.image.url(:thumb), :class => 'fixed-size-150'
          /   - elsif current_user.image.to_s != ""
          /     = image_tag current_user.image.url(:thumb), :class => 'fixed-size-150'
          /   - else
          /     = image_tag 'user_placeholder.png', :class => 'fixed-size-150'
          

          %div
            %input#profileImageInput{:type => "file"}
          %div{"ng-show" => "profileImage"}
            //.cropArea
            //  %img-crop{"area-type" => "square", "result-image-size" => "150", :image => "myImage", "result-image" => "myCroppedImage"}
            .cropArea#cropAreaProfileImage
              %img-crop{"area-min-size"=>"25", "area-type" => "square",:image => "profileImage", "result-image" => "profileCroppedImage"}

          %div{"ng-hide" => "profileImage"}
            %img{"ng-src" => "{{user.image.url}}", :class=>'thumbnail fixed-size-150'}



        .col-sm-7.no_right_padding
          %strong
            = t('project_creator').upcase
          - if(can?(:manage, @project.author))
            %small
              = link_to t('edit'), edit_profile_path(@project.author.id)

          %p.content-block-lightgreen.creator-block-fix
            = t('author.name') + ':'
            / %input{:name => 'user[name]', :placeholder => 'User name'}
            / = link_to(current_user.name, profile_path(current_user))
            %input{'ng-model' => 'user.name', "data-autosize-input"=>'{ "space": 0 }', placeholder: 'User name', maxlength: "20", "tabindex" => "16", class: 'nowidth'}
          %p.content-block-lightgreen.creator-block-fix
            = t('author.country') + '/' + t('author.city') + ':'
            - country = current_user.country.nil? ? '' : current_user.country
            - city = current_user.city.nil? ? '' : current_user.city
            - if((city.name != '') && (country.name != ''))
              = country.name.to_s + ' / ' + city.name.to_s
            - elsif(country.name != '')
              = country.name.to_s
            - elsif(city.name != '')
              = city.name.to_s

          %p.content-block-lightgreen.creator-block-fix
            = t('project.location') + ':'
            /%input{'ng-model' => 'project.country', id: 'country1', "data-autosize-input"=>'{ "space": 0 }', placeholder: 'Project country', maxlength: "20", "tabindex" => "16", class: 'nowidth'}
            %select{'ng-model' => 'project.country_id', 'ng-options' => "country.id as country.name for country in countries", 'ng-change'=>'change(project.country_id)'}
            / = f.text_field :country, id: 'country1', "data-autosize-input"=>'{ "space": 0 }', placeholder: 'Project country', maxlength: "20", "tabindex" => "16", class: 'nowidth'
      /TODO ADD SELECT for country and country from Short form
      .row.disable-input-style
        .col-sm-12.no_right_padding
          .thumbnail.padding-all-sm.fixed-height-158.content-background-lightpurple
            %strong
              = t('project_brief')
            %p
              %textarea{'ng-model' => 'project.tweet', id:'tweet', rows: '6', maxlength: '140', placeholder: t('project.tweet'), "tabindex" => "4"}
              / = f.text_area :tweet, id:'tweet', rows: '6', maxlength: '140', placeholder: t('project.tweet'), "tabindex" => "4"
              .remaining-symbols-textarea#tweet_counter
      %input.btn.btn-primary.pull-right{:type => "submit", :value => "Submit author part"}

  .col-sm-7.col-md-7
    %div{'ng-controller' => 'ImageController'}
      %form{:name => 'projectImageForm', 'ng-submit' => 'saveImage()'}
        %div
          %input#fileInput{:type => "file"}
        %div{"ng-show" => "myImage"}
          //.cropArea
          //  %img-crop{"area-type" => "square", "result-image-size" => "150", :image => "myImage", "result-image" => "myCroppedImage"}
          .cropArea#cropAreaProjectImage
            %img-crop{"result-image-size"=>"642", "area-type" => "rectangle", :image => "myImage", "result-image" => "myCroppedImage",  "aspect-ratio"=>"1.638"}

        %div{"ng-hide" => "myImage"}
          %img{"ng-src" => "{{project.image.url}}", height: "329", width: "529"}
        //%div Cropped Image:
        //%div{"ng-if" => "myImage"}
        //  %img{"ng-src" => "{{myCroppedImage}}"}
        
        %input.btn.btn-primary.pull-right{:type => "submit", :value => "Submit image"}

    / = form_for :project, url: project_path(@project), multipart: true, method: :patch, :html => { :id => '#create_form', :class => 'form-horizontal', :role => 'form' } do |f|
    /   %a.disable-input-style{:href=>'javascript:;'}
    /     .text-center
    /       - if @project.image?
    /         %div
    /           .fileinput.fileinput-new{"data-provides" => "fileinput"}
    /             .fileinput-preview.thumbnail{"data-trigger" => "fileinput", :style => "width: 539px; height: 329px;"}
    /               %img{:alt => "...", "src" => @project.image.url(:project_profile)}
    /             %div
    /               %span.btn.btn-file.file-input
    /                 / %input{type: 'file', name: 'image', onchange: "angular.element(this).scope().uploadFile(this.files)"}
    /                 = f.file_field :image
    /       - else
    /         =# TODO Image croping, not working yet
    /         / %input#demo{:name => "project[image]", :type => "hidden"}

    /         .fileinput.fileinput-new{"data-provides" => "fileinput"}
    /           .fileinput-preview.thumbnail{"data-trigger" => "fileinput", :style => "width: 539px; height: 329px;vertical-align: middle;display: table-cell;"}
    /             %div Image upload 1024x768
    /             / %img{:alt => "...", "src" => "holder.js/539x329"}
    /           %div
    /             %span.btn.btn-file.file-input
    /               / %input{type: 'file', name: 'image', onchange: "angular.element(this).scope().uploadFile(this.files)"}
    /               = f.file_field :image
    /   %input.btn.btn-primary.pull-right{:type => "submit", :value => 'Save image(page refresh)'}
    /   =# f.submit 'Save image(page refresh)', :class => 'btn btn-default'

app/views/projects/edit/_blockAuthor.html.haml
.col-sm-12.col-md-12.top-buffer.project-content-block
  = render partial: 'projects/edit/author'
  .col-sm-12.col-md-12
    .col-sm-4.col-md-4.no_padding
      = render partial: 'social_links'
    .col-sm-1.col-md-1
      .pull-right
        %a{ 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Like', :href => 'javascript:;' }
          %i.glyphicon.glyphicon-star-empty
  

app/views/projects/edit/_blockCreator.html.haml
%form{:name => 'projectCreatorForm', 'ng-submit' => 'saveCreator()'}
  =#<!-- CREATOR DETAILS -->
  .col-sm-12.col-md-12.top-buffer.project-content-block.bottom-buffer.disable-input-style
    .col-sm-6.col-md-6
      .col-sm-6.col-md-6.author-title
        %h1
          = t('creator_details')
          /TODO Remove or no
          / - if(can?(:manage, @project))     
          /   - if !@project.published? and !@project.closed? and !@project.on_review? 
          /     - if user_signed_in?
          /       %small
          /         = link_to t('project.modify'), edit_project_path(@project)
      .col-sm-6.col-md-6.no_left_padding
        %a{:href=>'javascript:;', :class=>'thumbnail fixed-size-200'}
          - if @project.author and @project.author.image?
            = image_tag @project.author.image.url(:thumb), :class => 'fixed-size-200' 
          - elsif current_user.image.to_s != ""
            = image_tag current_user.image.url(:thumb), :class => 'fixed-size-200' 
          - else
            = image_tag 'user_placeholder.png', :class => 'fixed-size-200'
    .col-sm-6.col-md-6.no_left_padding
      %p.content-block-lightgreen.creator-block-fix
        = t('author.name') + ':'
        = link_to(current_user.name, profile_path(current_user))
      %p.content-block-lightgreen.creator-block-fix
        = t('author.country') + '/' + t('author.city') + ':'
        - country = current_user.country.nil? ? '' : current_user.country
        - city = current_user.city.nil? ? '' : current_user.city
        - if((city.name != '') && (country.name != ''))
          = country.name.to_s + ' / ' + city.name.to_s
        - elsif(country.name != '')
          = country.name.to_s
        - elsif(city.name != '')
          = city.name.to_s
      %p.content-block-lightgreen.creator-block-fix
        = t('project.website') + ':'
        %input{'ng-model' => 'project.website', "data-autosize-input"=>'{ "space": 10 }', placeholder: 'Website(optional)',:type => 'url', maxlength: "40", "tabindex" => "6", class: 'nowidth'}
        / = f.text_field :website, "data-autosize-input"=>'{ "space": 10 }', placeholder: 'Website(optional)',:type => 'url', maxlength: "40", "tabindex" => "6", class: 'nowidth'
        / %input.nowidth{:name => 'project[website]', :placeholder => 'Website(optional)',:type => 'url', "data-autosize-input"=>'{ "space": 0 }', maxlength: "40"}
        %br (Optional)

      %p.content-block-lightgreen.creator-block-fix
        = t('project.location') + ':'
        /%input{'ng-model' => 'project.country', id: 'country3', "data-autosize-input"=>'{ "space": 0 }', placeholder: 'Project country', maxlength: "20", "tabindex" => "16", class: 'nowidth'}
        %select{'ng-model' => 'project.country_id', 'ng-options' => "country.id as country.name for country in countries", 'ng-change'=>'change(project.country_id)'}
        / = f.text_field :country, id: 'country3', "data-autosize-input"=>'{ "space": 0 }', placeholder: 'Project country', maxlength: "20", "tabindex" => "16", class: 'nowidth'
    .col-sm-12.col-md-12
      .row.row-eq-height
        .col-sm-12.col-md-12
          %h3 
            = t('creator_biography')
          %textarea{'ng-model' => 'project.creator_biography',rows: '10', maxlength: '1255', placeholder: "Please, add information about creator", "tabindex" => "7", onclick: 'textAreaAdjust(this)'}
          / = f.text_area :creator_biography, id:'creator_biography',rows: '10', maxlength: '1255', placeholder: "Please, add information about creator", "tabindex" => "7", onclick: 'textAreaAdjust(this)'
          / %textarea{name: "project[creator_biography]", rows: "auto", maxlength: "1255", id: "creator_biography", placeholder: "Please, add information about creator", "tabindex" => "6"}

    .col-sm-4.col-md-4.no_padding.pull-right
      = render partial: 'social_links'
  =#<!-- CREATOR DETAILS END -->
  %input.btn.btn-primary.pull-right{:type => "submit", :value => "Submit creator part"}

app/views/projects/edit/_blockDetails.html.haml
%form{:name => 'projectDetailsForm', 'ng-submit' => 'saveDetails()'}
  .col-sm-12.col-md-12.top-buffer.project-content-block
    .row.row-eq-height
      .col-sm-9.col-md-9.no_right_padding
        %h4.big-title-blue.text-center
          = t('main_details').upcase
          - if(can?(:manage, @project))
            - if !@project.published? and !@project.closed? and !@project.on_review? 
              - if user_signed_in?
                %small
                  = link_to t('project.modify'), edit_project_path(@project)
        .col-sm-12
          %textarea{'ui-tinymce' => "tinymceOptions", 'ng-model' => 'project.description', "tabindex" => "5",:rows => 30}
          / %textarea{'ng-model' => 'project.description', :class => "tinymce", "tabindex" => "5",:rows => 30}
          / = f.text_area :description, :class => "tinymce", "tabindex" => "5",:rows => 30
      .col-sm-3.col-md-3.right-col
        %h3
          = t('rewards').upcase
        .col-sm-12.col-md-12{"ng-repeat" => "reward in project.rewards | orderBy:'per_amount'"}
          = render :partial => 'projects/edit/reward', :locals => { hideText: ''}
        / - @project.rewards.sort.each do |reward|
        /   = render :partial => 'projects/reward', :locals => { reward: reward, hideText: '' }
  %input.btn.btn-primary.pull-right{:type => "submit", :value => "Submit details part"}

app/views/projects/edit/_blockMain.html.haml
%form{:name => 'projectMainForm', 'ng-submit' => 'saveMain()'}
  =#<!-- MAIN PART -->
  .col-sm-10.col-md-10.no_left_padding.big-top-buffer.disable-input-style
    .project-title
      / = f.text_field :name, id: 'project_name1', 'data-autosize-input' => '{ "space": 10 }', placeholder: t('project.name'), maxlength: '70', 'tabindex' => '1'
      %input{'ng-model' => 'project.name', 'data-autosize-input' => '{ "space": 10 }', placeholder: t('project.name'), maxlength: '70', 'tabindex' => '1', id: 'project_counter1'}
      .remaining-symbols-input#project_counter1
    .project-category
      %small
        = t('project.category').upcase + ':'

      %select{'ng-model' => 'project.category_ids', 'ng-options' => "category.id as category.name for category in categories",:multiple=>true, :class=>'selectpicker'}

      / = f.collection_select(:category_ids, Category.all, :id, :name, {}, {:multiple=>true, :class=>'selectpicker'})
  .col-sm-2.col-md-2.big-top-buffer
    %input.btn.btn-primary{:type => "submit", :value => "Submit main part"}
.col-sm-12.col-md-12.project-content-block.top-buffer
  = render partial: 'projects/edit/main'

app/views/projects/edit/_blockRewards.html.haml
=#<!-- REWARDS -->
.col-sm-12.col-md-12.top-buffer.project-content-block
  = render partial: 'projects/edit/rewards'
  / - if can?( :manage, @project.author)
  /   = link_to t('edit_author'), edit_profile_path(@project.author), :class => 'b-project__fill-author-info-btn btn btn-info'
=#<!-- REWARDS END -->

app/views/projects/edit/_reward.html.haml
.col-sm-12.col-md-12.no_left_padding.big-top-buffer.disable-input-style
  %h4
    %strong
      = t('reward.reward_for').upcase
      {{reward.per_amount}}+
      {{project.currency_id}}
      / = @project.currency.key unless @project.currency.nil?
  %span.reward-small.bottom-buffer-50{class: hideText}
    %div {{reward.description}}
    %p{'ng-show' => 'reward.image'}
      %img{'ng-src' => "{{reward.image.thumb.url}}", 'ng-show' => 'reward.image', class: 'img-rounded'}
      / = image_tag reward.image.url(:thumb), class: 'img-rounded'
    
  - if(can?(:manage, @project))     
    - if !@project.published? and !@project.closed? and !@project.on_review? 
      - if user_signed_in?
        %p
          %button.btn.btn-primary{'ng-click' => "editReward(reward)", type: 'button'} Edit
          %button.btn.btn-danger{'ng-click' => "deleteReward(reward)", type: 'button'} Delete
  /         = link_to t('reward.edit_reward'), edit_project_reward_path(reward.project.id, reward.id), :class => 'btn btn-info'
  /         = link_to t('reward.delete_reward'), project_reward_path(reward.project.id, reward.id), method: :delete, :class => 'btn btn-link'