config/routes.rb
Bullcentury::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/:locale' => 'home#index'

  scope '(:locale)', locale: /ru|ua|en|hu/ do
    root  to: 'home#index'
    get 'how_it_works', :to => 'home#how_it_works'
    get 'quick_start', :to => 'home#quick_start'
    get 'university', :to => 'home#university'
    get 'faq', :to => 'home#faq'
    get 'rules', :to => 'home#rules'
    get 'company', :to => 'home#company', :as =>  :company
    get 'mentors', :to => 'home#mentors'
    match '/feedbacks',     to: 'feedbacks#new', via: 'get'
    resources "feedbacks", only: [:new, :create]

    get 'receive_money', to: 'profiles#receive_money', as: 'receive_money'
    get 'receive_money_success', to: 'profiles#receive_money_success', as: 'receive_money_success' #temp
    get 'invest_project', to: 'profiles#invest_project', as: 'invest_project'
    get 'refunds', to: 'profiles#refunds', as: 'refunds'
    get 'activities_report', to: 'profiles#activities_report', as: 'activities_report'
    get 'my_project', to: 'profiles#my_project', as: 'my_project'
    get 'promote_project', to: 'profiles#promote_project', as: 'promote_project'
    get 'shipping', to: 'profiles#shipping', as: 'shipping'
    get 'profile_management', to: 'profiles#profile_management', as: 'profile_management'
    get 'update_cities', to: 'profiles#update_cities', as: 'update_cities'
    get 'receive_money_part2', to: 'profiles#receive_money_part2', as: 'receive_money_part2'

    get 'success', to: 'profiles#success'
    
    get  'dashboard', to: 'profiles#dashboard', as: 'dashboard'
    get  'profiles/:id', :to => 'profiles#show', :as =>  :profile
    get  'profiles/:id/edit', :to => 'profiles#edit', :as =>  :edit_profile
    post 'profiles/update', :to => 'profiles#update'
    get 'categories/:key', :to => 'categories#show', :as => :category

    resources :pledge_transactions
    resources :projects do
      resources :rewards
      resources :authors

      member do
       get 'publish'
       get 'stop'
       get 'agreement_page'
     end
      collection do
        get 'leisure'
        get 'media'
        get 'art'
        get 'crazy'
        get 'innovation'
        get 'social'
      end
    end
    namespace :api, defauts: {format: :json} do
      resources :projects, only: [:index, :show, :update] do
        resources :rewards, only: [:index, :show, :update, :create, :destroy]
      end
      resources :currencies, only: [:index]
      resources :categories, only: [:index]
      resources :cities, only: [:show, :index]
      resources :countries, only: [:index]
      resources :profiles, only: [:show, :update]
    end

  end

  devise_for :users, :controllers => {  confirmations: 'confirmations', :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project

  validates :per_amount, presence: true
  validates :description, presence: true
  validates :project_id, presence: true
  mount_uploader :image, ImageUploader

end

app/controllers/api/rewards_controller.rb
class Api::RewardsController < ApplicationController
  skip_before_filter :verify_authenticity_token  
  def index
    render json: rewards
  end

  def show
    render json: reward
  end

  def create
    params[:reward] = convert_data_uri_to_upload(params[:reward])

    reward = allRewards.create!(reward_params)
    render json: reward
  end

  # def update
  #   @product = Product.find(params[:id])
  #   if @product.update_attributes(product_params)
  #     redirect_to @product
  #   else
  #     render :index
  #   end
  # end

  def update
    params[:reward] = convert_data_uri_to_upload(params[:reward])

    reward.update_attributes(reward_params)
    render nothing: true
  end

  #def delete
  #  render json: product
  #end

  def destroy
     reward.destroy
     render nothing: true
  end

  # def new
  #   @product = Product.new
  #   @categories = Category.all
  # end

  # def create
  #   @product = Product.new(product_params)
  #   if @product.save
  #     redirect_to products_path
  #   end
  # end

  # def edit
  #   @product = Product.find(params[:id])
  #   @categories = Category.all
  # end


  



  # def destroy
  #   Product.find(params[:id]).destroy
  #   redirect_to products_path
  # end

  private
  def reward
  	@reward ||= Reward.find(params[:id])
  end

  def rewards
  	# @rewards ||= Reward.find_by_project_id(params[:project_id]) 
  	@rewards ||= Reward.all(:conditions => ["project_id = ?", params[:project_id]])
  end

  def allRewards
    @allRewards ||= Reward.all  
  end

  def reward_params
    params.require(:reward).permit(
      :per_amount, 
      :description, 
      :image, 
      :remote_image_url, 
      :project_id
    )
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @reward = Reward.new :project_id => params[:project_id]
  end

  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      @project = Project.find(@reward.project.id)
      redirect_to @project
    else
      render 'new'
    end
  end

  def index
    @rewards = Reward.find_by_project_id(params[:project_id])
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find(params[:id])
    if @reward.update(params[:reward].permit(:per_amount, :description, :image,))
      if params[:reward][:delete_image] == "1"
        @reward.remove_image!
        @reward.save
        puts "DELETING"
      end
      @project = Project.find(@reward.project.id)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy

    redirect_to projects_path
  end

  private

  def reward_params
    params.require(:reward).permit(:per_amount, :description, :image, :remote_image_url, :project_id)
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.haml
= form_for :reward, url: url, multipart: true, method: method, :html => {:class => 'form-horizontal', :role => 'form'} do |f|
  - if @reward.errors.any?
    #error_explanation
      %h2
        = pluralize(@reward.errors.count, 'error')
        prohibite
        this reward from being saved:
      %ul
        - @reward.errors.full_messages.each do |msg|
          %li= msg
  = f.hidden_field :project_id, value: @reward.project_id
  .form-group.row
    = f.label :image, t('reward.image'), :class => 'col-sm-5'
    .col-sm-7
      = image_tag(@reward.image.url(:thumb)) if (@reward and @reward.image?)
      = f.file_field :image, class: 'form-control'
      %small.help-block
        = t('reward.image_hint')
  .form-group.row
    = f.label :image, t('reward.delete_image'), :class => 'col-sm-5'
    .col-sm-7
      = check_box_tag "reward[delete_image]"
  .form-group
    = f.label :per_amount, t('reward.per_amount'), :class => 'col-sm-5'
    .col-sm-7
      = f.text_field :per_amount, :class => 'form-control',:type => 'number', :required => 'required'
  .form-group
    = f.label :description, t('reward.description'), :class => 'col-sm-5'
    .col-sm-7
      = f.text_area :description, rows: 10, :class => 'form-control', :required => 'required'
  .form-group
    .col-sm-offset-5.col-sm-7
      = f.submit t('reward.save'), :class => 'btn btn-default'
      = link_to t('back_to_project'), project_path(@reward.project), :class => 'btn btn-link'

app/views/rewards/_form_angular.html.haml
%form{:name => 'projectRewardForm',:id => 'projectRewardForm', 'ng-submit' => 'saveReward()'}
  .col-sm-12.col-md-12.no_left_padding.big-top-buffer
    %div{'ng-show' => '{{reward.errors}}'}
      #error_explanation
        %h2
          = pluralize('{{reward.errors.length}}', 'error')
          prohibite
          this reward from being saved:
        %ul{'ng-repeat' => 'msg in reward.errors.full_messafes'}
          %li {{msg}}
    / = f.hidden_field :project_id, value: @reward.project_id
    /TODOANG Image for reward
    / .form-group.row
    / = f.label :image, t('reward.image'), :class => 'col-sm-5'
    / .col-sm-7
    / = image_tag(@reward.image.url(:thumb)) if (@reward and @reward.image?)
    / = f.file_field :image, class: 'form-control'
    / %small.help-block
    / = t('reward.image_hint')
    / .form-group.row
    / = f.label :image, t('reward.delete_image'), :class => 'col-sm-5'
    / .col-sm-7
    / = check_box_tag "reward[delete_image]"
    .form-group
      %label 
        =t('reward.per_amount') 
      %input{'ng-model' => 'newReward.per_amount', type: 'number', :required => 'required', class: "form-control", min: 1}
    .form-group
      %label 
        =t('reward.description') 
      %textarea{'ng-model' => 'newReward.description', rows: 10, :class => 'form-control', :required => 'required'}
      / = f.label :description, t('reward.description'), :class => 'col-sm-5'
      .col-sm-7
        / = f.text_area :description, rows: 10, :class => 'form-control', :required => 'required'
    .form-group
      /%label 
      /  =t('reward.image') 
      /%input{'ng-model' => 'newReward.image', type: 'number', :required => 'required', class: "form-control", min: 1}


      %div
        %input#rewardImageInput{:type => "file"}
      %div{"ng-show" => "rewardImage"}
        //.cropArea
        //  %img-crop{"area-type" => "square", "result-image-size" => "150", :image => "myImage", "result-image" => "myCroppedImage"}
        .cropArea#cropAreaRewardImage
          %img-crop{"area-min-size"=>"25", "area-type" => "square",:image => "rewardImage", "result-image" => "rewardCroppedImage"}

      %div{"ng-hide" => "rewardImage"}
        %img{"src" => "{{newReward.image.url}}", class: "reward-form"}

  .col-sm-12.col-md-12
    %input.btn.btn-success.pull-right{:type => "submit", :value => "Save reward"}
    %button.btn.btn-primary.pull-right{'ng-click' => "clearForm()", type: 'button'} Clear form  

app/views/rewards/edit.html.haml
%h1= t('reward.edit_reward')
= render :partial => 'rewards/form', locals: {url: project_reward_path(@reward.project.id, @reward), method: :patch, reward: @reward}

app/views/rewards/index.html.erb
<h1>Rewards#index</h1>
<p>Find me in app/views/rewards/index.html.erb</p>

app/views/rewards/new.html.haml
%h1= t('reward.add_new_reward')
= render :partial => 'rewards/form', locals: {url: project_rewards_path, method: :post}