config/routes.rb
Bullcentury::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/:locale' => 'home#index'

  scope '(:locale)', locale: /ru|ua|en|hu/ do
    root  to: 'home#index'
    get 'how_it_works', :to => 'home#how_it_works'
    get 'quick_start', :to => 'home#quick_start'
    get 'university', :to => 'home#university'
    get 'faq', :to => 'home#faq'
    get 'rules', :to => 'home#rules'
    get 'company', :to => 'home#company', :as =>  :company
    get 'mentors', :to => 'home#mentors'
    match '/feedbacks',     to: 'feedbacks#new', via: 'get'
    resources "feedbacks", only: [:new, :create]

    get 'receive_money', to: 'profiles#receive_money', as: 'receive_money'
    get 'receive_money_success', to: 'profiles#receive_money_success', as: 'receive_money_success' #temp
    get 'invest_project', to: 'profiles#invest_project', as: 'invest_project'
    get 'refunds', to: 'profiles#refunds', as: 'refunds'
    get 'activities_report', to: 'profiles#activities_report', as: 'activities_report'
    get 'my_project', to: 'profiles#my_project', as: 'my_project'
    get 'promote_project', to: 'profiles#promote_project', as: 'promote_project'
    get 'shipping', to: 'profiles#shipping', as: 'shipping'
    get 'profile_management', to: 'profiles#profile_management', as: 'profile_management'
    get 'update_cities', to: 'profiles#update_cities', as: 'update_cities'
    get 'receive_money_part2', to: 'profiles#receive_money_part2', as: 'receive_money_part2'

    get 'success', to: 'profiles#success'
    
    get  'dashboard', to: 'profiles#dashboard', as: 'dashboard'
    get  'profiles/:id', :to => 'profiles#show', :as =>  :profile
    get  'profiles/:id/edit', :to => 'profiles#edit', :as =>  :edit_profile
    post 'profiles/update', :to => 'profiles#update'
    get 'categories/:key', :to => 'categories#show', :as => :category

    resources :pledge_transactions
    resources :projects do
      resources :rewards
      resources :authors

      member do
       get 'publish'
       get 'stop'
       get 'agreement_page'
     end
      collection do
        get 'leisure'
        get 'media'
        get 'art'
        get 'crazy'
        get 'innovation'
        get 'social'
      end
    end
    namespace :api, defauts: {format: :json} do
      resources :projects, only: [:index, :show, :update] do
        resources :rewards, only: [:index, :show, :update, :create, :destroy]
      end
      resources :currencies, only: [:index]
      resources :categories, only: [:index]
      resources :cities, only: [:show, :index]
      resources :countries, only: [:index]
      resources :profiles, only: [:show, :update]
    end

  end

  devise_for :users, :controllers => {  confirmations: 'confirmations', :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :how_it_works, :quick_start, :university, :faq, :rules, :company, :mentors, :feedback]

  def index
    @popular_projects = Project.where(state: 'set_for_publish')[0, 5]
    @successful_projects = Project.where(state: 'set_for_publish')[0, 3]

    @popular_projects = Array.new unless @popular_projects
    @successful_projects = Array.new unless @successful_projects
  end

  def how_it_works
  end

  def quick_start
  end

  def university
  end

  def faq
  end

  def rules
  end

  #TODO 
  def company
  end

  #TODO 
  def mentors
    @users = User.all[0, 5]
    @mentors = User.all[0, 3]
    # render json: {:mentors => @mentors}
    respond_to do |format|
      format.json { @mentors }
      format.html { render '/home/mentors' }
    end
  end

  #TODO
  def feedback
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_faq_en.html.haml
%br
%div
	%h5#index-a.mouse_pointer{:term => "index-a"}
		%span.green_darker_bold
			= t('infocenter.nav.index-a') + ':'
		BEFORE YOU START
%div{:term => "index-a"}
	%ul.dash
		%li Project rules / Policies
		%li How it works 
		%li Fees 
		%li Any charges apply to investors or donors? 
		%li Can foreign investors/donors participate to my project?
		%li Are there any time limits? 
		%li What if I don’t reach my goal? 
		%li How will I know if someone funds/donates my project? 
		%li Do I have to use my real name? 
		%li Who will invest or donate to my project? 
		%li Is BC work in my country?
%div
	%h5#index-b.mouse_pointer{:term => "index-b"}
		%span.green_darker_bold
			= t('infocenter.nav.index-b') + ':'
		CREATING A PROJECT
%div{:term => "index-b"}
	%ul.dash
		%li Is project video must required?  
		%li How to shoot my project video? (Video) 
		%li How many videos I can post for project?  
		%li What is fundamental?  
		%li How to set up an reward? (Video) 
		%li How many project pictures can I post in different section?  
		%li Can I edit project after proved and published?  
		%li What is project updates?  
%div
	%h5#index-c.mouse_pointer{:term => "index-c"}
		.empty
			%span.green_darker_bold
				= t('infocenter.nav.index-c') + ':'
			AFTER PROJECT PUBLISHED
%div{:term => "index-c"}
	%ul.dash
		%li Receiving Funds or Donations 
		%li Refund 
		%li What if my project failed? 
		%li What about taxes? 
%div
	%h5#index-d.mouse_pointer{:term => "index-d"}
		.empty
			%span.green_darker_bold
				= t('infocenter.nav.index-d') + ':'
			BETTER SUCCESS
%div{:term => "index-d"}
	%ul.dash
		%li Project video 
		%li Reward 
		%li Secrets to success 
		%li Promote my project / Share my campaign 
		%li BC University 

app/views/home/_faq_ru.html.haml
%br
%div
	%h5#index-a.mouse_pointer{:term => "index-a"}
		%span.green_darker_bold
			= t('infocenter.nav.index-a') + ':'
		ПЕРЕД НАЧАЛОМ
%div{:term => "index-a"}
	%ul.dash
		%li Правила проекта / Политика
		%li Как это работает
		%li Порядок оплаты 
		%li [RU] Any charges apply to investors or donors? 
		%li Могут ли иностранные инвесторы / спонсоры участвовать в моем проекте?
		%li Есть ли ограничения по времени? 
		%li Что делать, если я не достигну своей цели?
		%li Как я узнаю, что кто-то инвестирует / жертвует в мой ​​проект?
		%li Должен ли я использовать свое настоящее имя?
		%li Кто будет инвестировать или спонсировать мой проект?
		%li Работает BC в моей стране?
%div
	%h5#index-b.mouse_pointer{:term => "index-b"}
		%span.green_darker_bold
			= t('infocenter.nav.index-b') + ':'
		СОЗДАНИЕ ПРОЕКТА
%div{:term => "index-b"}
	%ul.dash
		%li Обязательно ли иметь видео проекта?  
		%li Как снимать видео проекта ? (Видео) 
		%li Сколько видео я могу разместить для проекта?
		%li Что является основополагающим? 
		%li Как настроить награду? (Видео)
		%li Сколько фотографий проекта можно разместить в разных разделах?
		%li Могу ли я редактировать проект после [RU] proved и публикации?
		%li Что такое обновления проекта? 
%div
	%h5#index-c.mouse_pointer{:term => "index-c"}
		.empty
			%span.green_darker_bold
				= t('infocenter.nav.index-c') + ':'
			ПОСЛЕ ПУБЛИКАЦИИ ПРОЕКТА
%div{:term => "index-c"}
	%ul.dash
		%li Получение средств или пожертвований
		%li Возврат
		%li Что делать, если мой проект не удался? 
		%li Что насчет налогов?
%div
	%h5#index-d.mouse_pointer{:term => "index-d"}
		.empty
			%span.green_darker_bold
				= t('infocenter.nav.index-d') + ':'
			[RU]BETTER SUCCESS
%div{:term => "index-d"}
	%ul.dash
		%li Видео проекта
		%li Награда 
		%li Секреты успеха
		%li [RU] Promote my project / Share my campaign 
		%li BC Университет 

app/views/home/_general_buttons_block.html.haml
= render partial: 'dashboard_button', locals: {image: 'back_arrow.png', title: 'back', page_url: profile_path(current_user)}
.col-sm-4
	%div.dashboard_icons{:onclick => "myFunction()"} 
		= link_to('javascript:;') do
			= image_tag('print_icon.png', height: '50')
	= t('print')
= render partial: 'dashboard_button', locals: {image: 'contact_icon.png', title: 'contact_us', page_url: 'javascript:;'}
:javascript
	function myFunction() {
	    window.print();
	}

app/views/home/_how_it_works_en.html.haml
.jumbotron
  %h2 What is Crowdfunding?
  %p
    Crowdfunding (alternately crowd financing, equity crowdfunding, crowd-sourced fundraising) is the collective effort of individuals who network and pool their money, usually via the Internet, to support efforts initiated by other people or organizations.
.jumbotron
  %h2 Who can create a project?
  %p
    Have you ever wanted to write your own music but needed financial support? Are you an artist who would like to show the world something new? Or maybe there is just this one thing that needs to be invented? We are here for you!
.jumbotron
  %h2 Who can fund a project?
  %p
    The people, who provide capital for these projects in exchange for certain rewards or ownership equity are referred to as angel investors.
    But how does it actually work? Simple!
.jumbotron
  %h2 How to build a profile?
  %p
    Everything starts with an idea. Using a specially provided form you are able to create your own project by inputting description and media materials. This is a serious step because the more thought out project is, the more interested will other people be in funding it. But no worries, there is always room for improvements and changes to increase chances in making your dream come true.
.jumbotron
  %h2 Process
  %p
    As soon as your project is added to our website it becomes public and any interested angel investor can provide their support by commenting, donating, rating and labeling. At this stage the project will start to accumulate feedback, based on which it can be modified.
.jumbotron
  %h2 Tracking
  %p
    Gradually as more angels would contribute their part to funding your project you will be able to track progress and see what amount is left until goal is reached.
.jumbotron
  %h2 Rewards
  %p
    After the project is funded all there is left is rewarding all those good people and making them just as happy.
.jumbotron
  %h2 Fees
  %p
    No membership fees
    Funding on Bull century is all-or-nothing
  %p
    Charity project fees for users from Former Soviet Republics and PRC: 4 % + payment processing fees
    Charity project fees for users from USA, Canada and EU for thyself or a friend: 6.9% + payment processing fees
    Charity project fees for users from USA, Canada and EU for favorite or non-profit: 8.25% + payment processing fees
    Non-charity project for users from Former Soviet Republics, PRC, USA, Canada and EU: 4 % + payment processing fees
  %p
    Bull century doesn't issue refunds as transactions are between funders and creators directly. Creators receive all funds (less fees) soon after their campaign ends.

app/views/home/_how_it_works_ua.html.haml
.jumbotron
  %h2 Що таке Краудфандінг?
  %p
    Краудфа́ндінг (народне фінансування, від англ. сrowd funding, сrowd — «натовп», funding — «финансування») — це колективна співпраця людей (бізнес-ангелів), які добровільно об’єднують свої гроші або інші ресурси разом, як правило через інтернет, щоби підтримати зусилля інших людей та організацій.
.jumbotron
  %h2 Хто може створити проект?
  %p
    Чи виникало в Вас бажання писати музику, але Вам не вистачало фінансової підтримки? Можливо Ви художник, якому є що показати світові? Чи може є ще щось невинайдене? Ми тут, щоб допомогти Вам!
.jumbotron
  %h2 Хто може фінансувати проект?
  %p
    Фінансуванням проектів займаються бізнес-ангели — приватні інвестори, які вкладають гроші в інноваційні проекти в обмін на повернення вкладень та долю у капіталі.
    Але як це все працює? Все дуже просто!
.jumbotron
  %h2 Як створити профіль?
  %p
    Все починається з ідеї. За допомогою спеціальної анкети Вам надається можливість створити свій проект, у яку Ви зможете ввести опис та додати до неї аудіо- та відеоматеріали. Це дуже важливий крок, бо чим краще проект продуманий, тим легше буде зацікавити потенційних спонсорів. Тим не менш, завжди є можливість редагувати та покращувати проект, тим самим відвищуючи його шанси.
.jumbotron
  %h2 Процес
  %p
    Після того, як Ваш проект доданийдо нас на сайт, він стає публічним, та будь-який інший заінтересований спонсор або бізнес-ангел може забезпечити свою подтрімку комментуючи, вкладаючи кошти або підвищуючи рейтинг проекту. На цьому етапі у проекта з’являться перші відгуки, на основі яких його можна покращити або змінити.
.jumbotron
  %h2 Стан проекту
  %p
    У Вас буде можливість спостерігати за станом проекту, хто і яку сумму вклав, а такоже якої сумми не вистачає для його реалізації.
.jumbotron
  %h2 Винагорода
  %p
    Після того, як проект будет повністю проспонсований, настає час винагород для людей, котрі зробили свій внесок у розвиток проекту.
.jumbotron
  %h2 Правила
  %p
    Ніяких членських взносів.
    Фінансування на BullCentury проводиться тільки у випадку, якщо необхідна сумма досягнута.
  %p
    Плата для користувачів з країн колишнього Радянського союзу та КНР за благодійні проекти: 4% + коміссія.
    Плата для користувачів з США, Канади та країн Євросоюзу за власні благодійні проекти або благодійні проекти друзів: 6.9% + коміссія.
    Плата для користувачів з США, Канади та країн Євросоюзу за інші не коммерційні проекти: 8.25% + коміссія.
    Плата для користувачів з країн колишнього Радянського союзу, КНР, США, Канади та Євросоюзу за коммерційні проекти: 4% + коміссія.
  %p
    BullCentury не повертає гроші, так як усі транзакції проходять напряму між творцями проектів та спонсорами. Творці проектів отримують сумму за вирахуванням оплати BullCentury незабаром після завершення кампанії.

app/views/home/_navigation.html.erb
<ul class="list-group list-unstyled">
  <li class="list-group-item"><%= link_to t('project.listing'), controller: 'projects' %></li>
  <li class="list-group-item"><%= link_to t('project.create'), new_project_path %></li>
  <li class="list-group-item"><%= link_to t('how_it_works'), how_it_works_path %></li>
  <li class="list-group-item"><%= link_to t('bc_university'), university_path %></li>
  <li class="list-group-item"><%= link_to t('faq'), faq_path %></li>
</ul>

app/views/home/_university_banner.html.haml
- content_for :banner do
	.imagewrap.shadow
		= image_tag "banners/bc_univer.png", :class => "project-banner", :usemap => "#univer_banner", :alt => "univer_banner", :hidefocus => "true"
		%map{:name => "univer_banner"}
			%area{:alt => "Video", :coords => "577,209,588,221,428,361,405,358", :href => university_url + "#video", :shape => "poly"}
			%area{:alt => "Lelev 3", :coords => "580,238,603,263,495,359,434,361", :href => "#", :shape => "poly"}
			%area{:alt => "Lelev 2", :coords => "668,215,690,242,551,365,502,357", :href => "#", :shape => "poly"}
			%area{:alt => "Lelev 1", :coords => "733,185,765,205,631,391,599,370", :href => "#", :shape => "poly"}
			%area{:alt => "BC University", :coords => "768,239,961,239,961,271,768,271", :href => university_url, :shape => "poly"}
			%area{:alt => "Success", :coords => "717,274,946,274,946,311,717,311", :href => "#", :shape => "poly"}
			%area{:alt => "BC Century", :coords => "698,316,984,316,984,352,698,352", :href => root_url, :shape => "poly"}
			%area{:alt => "Quick start", :coords => "664,359,927,356,927,391,664,391", :href =>  quick_start_url, :shape => "poly"}
		%div.button_hover_green
			= link_to t('project.add_new_project').upcase(), new_project_url, :class => "button_link_right_top btn-lg"

app/views/home/_university_nav.html.haml
%ul.nav.nav-tabs.nav-green
	%li.active
		%a{"data-toggle" => "tab", :href => "#intro"} 
			= t('university.intro')
	%li
		%a{"data-toggle" => "tab", :href => "#level_1"} 
			= t('university.level1')
	%li
		%a{"data-toggle" => "tab", :href => "#level_2"} 
			= t('university.level2')
	%li
		%a{"data-toggle" => "tab", :href => "#video"} 
			= t('university.video')

app/views/home/index.html.erb
<% content_for :part1 do %>
  <!-- <div class="shadow"> -->
  <%= render partial: 'banner_slider_full_width'%>
  <%#= render partial: 'banner_video' %>


    <%#= image_tag I18n.locale == :ru ? 'front_banner_ru.jpg' : 'front_banner_en.jpg', :class => 'img-rounded' %>
  <!-- </div> -->
<% end %>



<div class="grid-nav-container row text-center">
  <div class="col-sm-4 col-md-4">
    <div class="bright">
      <div class="grid-nav-item pink_gradient_left_bottom_to_right_center">
        <%= link_to projects_path do %>
          <div class="uppercase"><%=  t('project.listing') %></div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-md-4">
    <div class="bright">
      <div class="grid-nav-item blue_gradient_right_bottom_to_left_center">
        <%= link_to mentors_path do %>
          <div class="uppercase"><%= t('mentors.mentors_title') %></div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-md-4">
    <div class="bright">
      <div class="grid-nav-item green_gradient_left_bottom_to_right_center">
        <%= link_to university_path do %>
          <div class="uppercase"><%= t('bc_university') %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="grid-nav-container row text-center">
  <div class="col-sm-4 col-md-4">
    <div class="grid-nav-item m-bg-pink">
      <%= link_to category_path('art') do %>
        <ul class="left_top list_bullet">
          <li><%= t('paint') %></li>
          <li><%= t('literature') %></li>
          <li><%= t('theater') %></li>
        </ul>
        <div class="uppercase"><%= t('art')%></div>
        <div class="right_bottom uppercase"><%= t('more')%>  <%= image_tag('bullet1.png') %></div>
      <% end %>
    </div>
  </div>
  <div class="col-sm-4 col-md-4">
    <div class="grid-nav-item m-bg-blue">
      <%= link_to category_path('media') do %>
        <ul class="left_top list_bullet">
          <li><%= t('music') %></li>
          <li><%= t('movie') %></li>
          <li><%= t('photo') %></li>
        </ul>
        <div class="uppercase"><%= t('media') %></div>
        <div class="right_bottom uppercase"><%= t('more') %>  <%= image_tag('bullet1.png') %></div>
      <% end %>
    </div>
  </div>
  <div class="col-sm-4 col-md-4">
    <div class="grid-nav-item m-bg-green">
      <%= link_to category_path('innovation') do %>
        <ul class="left_top list_bullet">
          <li><%= t('product') %></li>
          <li><%= t('design') %></li>
          <li><%= t('technology') %></li>
        </ul>
        <div class="uppercase"><%= t('innovation') %></div>
        <div class="right_bottom uppercase"><%= t('more') %>  <%= image_tag('bullet1.png') %></div>
      <% end %>
    </div>
  </div>
</div>

<div class="grid-nav-container row text-center">
  <div class="col-sm-4 col-md-4">
    <div class="grid-nav-item m-bg-yellow">
      <%= link_to category_path('crazy') do %>
        <ul class="left_top list_bullet">
          <li><%= t('talent') %></li>
          <li><%= t('funny') %></li>
          <li><%= t('never_seen') %></li>
        </ul>
        <div class="uppercase"><%= t('crazy') %></div>
        <div class="right_bottom uppercase"><%= t('more') %>  <%= image_tag('bullet1.png') %></div>
      <% end %>
    </div>
  </div>
  <div class="col-sm-4 col-md-4">
    <div class="grid-nav-item m-bg-green">
      <%= link_to category_path('leisure') do %>
        <ul class="left_top list_bullet">
          <li><%= t('travel') %></li>
          <li><%= t('cook') %></li>
          <li><%= t('adventure') %></li>
        </ul>
        <div class="uppercase"><%= t('leisure') %></div>
        <div class="right_bottom uppercase"><%= t('more') %>  <%= image_tag('bullet1.png') %></div>
      <% end %>
    </div>
  </div>
  <div class="col-sm-4 col-md-4">
    <div class="grid-nav-item m-bg-blue">
      <%= link_to category_path('charity') do %>
        <ul class="left_top list_bullet">
          <li><%= t('social') %></li>
          <li><%= t('community') %></li>
          <li><%= t('eco')%></li>
        </ul>
        <div class="uppercase"><%= t('charity') %></div>
        <div class="right_bottom uppercase"><%= t('more') %>  <%= image_tag('bullet1.png') %></div>
      <% end %>
    </div>
  </div>
</div>

<div class="line-separator"></div>

<!-- Popular Projects -->
<div class="panel panel-danger home-page__popular-projects-container">

  <div class="row projects_rows">
    <%= render partial: 'projects/projects_block', locals: {
      key: 'popular',
      projects: @popular_projects,
      caption: t('popular_projects'),
      is_separator_hidden: true } %>
    <%= render partial: 'projects/projects_block', locals: {
      key: 'successful',
      projects: @successful_projects,
      caption: t('successful_projects'),
      is_separator_hidden: false } %>
  </div>

  <!-- <div class="panel-heading">
    <h3 class="panel-title">
      <#%= t('popular_projects') %>
      <#%= link_to t('all_projects'), projects_path, :class => 'pull-right' %>
    </h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <#% unless @popular_projects.empty? %>
          <#% @popular_projects.each do |project| %>
            <div class="col-sm-4 col-md-4">
              <#%= render :partial => 'projects/project', :locals => { project: project } %>
            </div>
          <#% end %>
      <#% else %>
        <div class="alert alert-warning text-center col-sm-offset-2 col-sm-8">
          <p><strong><%#= t('no_projects') %></strong></p>
          <p><%#= link_to t('create_popular_project'), new_project_path, :class => 'btn btn-info' %></p>
        </div>
      <#% end %>
    </div>
  </div> -->

</div>
<div class="col-sm-12 bottom-buffer-150">
<!-- End of Popular Projects -->

<!-- Successful Projects -->
<!-- <div class="panel panel-success home-page__successful-projects-container">
  <div class="panel-heading">
    <h3 class="panel-title">
      <#%= t('successful_projects') %>
      <#%= link_to t('all_projects'), projects_path, :class => 'pull-right' %>
    </h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <#% unless @successful_projects.empty? %>
          <#% @successful_projects.each do |project| %>
            <div class="col-sm-4 col-md-4">
              <#%= render :partial => 'projects/project', :locals => { project: project } %>
            </div>
          <#% end %>
      <#% else %>
        <div class="alert alert-warning text-center col-sm-offset-2 col-sm-8">
          <p><strong><#%= t('no_projects') %></strong></p>
          <p><#%= link_to t('create_successful_project'), new_project_path, :class => 'btn btn-info' %></p>
        </div>
      <#% end %>
    </div>
  </div>
</div>

<!-- End of Successful Projects -->

<!--Start video button-->
<!--<div class="row video_button text-center">
  <a href="<%= how_it_works_path %>">
    <div class="col-sm-6">
      <%= image_tag 'video_button_1_2.png', :class => 'bot' %>
      <%= image_tag 'video_button_1_1.png', :class => 'top' %>
      <div class="text text-left">
        <h4><%= t('video') %> 1</h4>
        <p><%= t('video_1') %></p>
      </div>
    </div>
  </a>
  <a href="<%= how_it_works_path %>">
    <div class="col-sm-6">
      <%= image_tag 'video_button_2_2.png', :class => 'bot' %>
      <%= image_tag 'video_button_2_1.png', :class => 'top' %>
      <div class="text text-left">
        <h4><%= t('video') %> 2</h4>
        <p><%= t('video_2') %></p>
      </div>
    </div>
  </a>
</div>-->
<!--End video button-->

<span id="top-link-block" class="hidden">
    <a href="#top" onclick="$('html,body').animate({scrollTop:0},'slow');return false;">
        <%= image_tag 'up_button.png' %>
    </a>
</span><!-- /top-link-block -->

<!-- horizontal slider -->
<script type="text/javascript">
  (function () {
    $(function() {
      $(".projects-carousel").each(function (i, element) {
        $(element).jCarouselLite({
          btnNext: $('.next', element)[0],
          btnPrev: $('.prev', element)[0],
          visible: 3,
          start: 0,
          circular: false
        });
      });
    });
  })()
</script>

app/views/home/quick_start.html.haml
%h1.col-sm-9.big-title.xbig-top-buffer= t('quick_start').upcase
.col-sm-10.col-md-10.col-sm-offset-1.big-top-buffer.text-center{ 'data-spy' => :scroll, 'data-target' => '#nav-quick-start'}
  .quick-arrow
  - if I18n.locale == :ua
    = image_tag "banners/quick_start_ua.png", :class => "scale_700"

  - if I18n.locale == :ru
    = image_tag "banners/quick_start_ru.png", :class => "scale_700"

  - if I18n.locale == :en
    = image_tag "banners/quick_start_en.png", :class => "scale_700"

  - if I18n.locale == :hu
    = image_tag "banners/quick_start_hu.png", :class => "scale_700"
.col-sm-12.no-padding.bottom-buffer-200.top-buffer-100{'data-spy' => :scroll, 'data-target' => '#nav-quick-start'}
  - if I18n.locale == :ua
    = render partial: 'home/quick_start_ua'

  - if I18n.locale == :ru
    = render partial: 'home/quick_start_ru'

  - if I18n.locale == :en
    = render partial: 'home/quick_start_en'

  - if I18n.locale == :hu
    = render partial: 'home/quick_start_hu'
%span#top-link-block.hidden
  %a{:href => "#top", :onclick => "$('html,body').animate({scrollTop:0},'slow');return false;"}
    =image_tag 'up_button.png'
/ /top-link-block
:javascript
  $(document).ready(function(){
    $('.mouse_pointer').click(function(){
      term = $(this).attr('term');
      //$(this).addClass('blue');
      //alert(term_text);
      $('.content').each(function(){    
        if ($(this).attr('term') == term){        
          if ($(this).css('display') == 'none'){
            $(this).css('display','block');
          }          
          else {
            $(this).css('display','none');
          }      
                      
        }
      });
    });
  });