config/routes.rb
Bullcentury::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/:locale' => 'home#index'

  scope '(:locale)', locale: /ru|ua|en|hu/ do
    root  to: 'home#index'
    get 'how_it_works', :to => 'home#how_it_works'
    get 'quick_start', :to => 'home#quick_start'
    get 'university', :to => 'home#university'
    get 'faq', :to => 'home#faq'
    get 'rules', :to => 'home#rules'
    get 'company', :to => 'home#company', :as =>  :company
    get 'mentors', :to => 'home#mentors'
    match '/feedbacks',     to: 'feedbacks#new', via: 'get'
    resources "feedbacks", only: [:new, :create]

    get 'receive_money', to: 'profiles#receive_money', as: 'receive_money'
    get 'receive_money_success', to: 'profiles#receive_money_success', as: 'receive_money_success' #temp
    get 'invest_project', to: 'profiles#invest_project', as: 'invest_project'
    get 'refunds', to: 'profiles#refunds', as: 'refunds'
    get 'activities_report', to: 'profiles#activities_report', as: 'activities_report'
    get 'my_project', to: 'profiles#my_project', as: 'my_project'
    get 'promote_project', to: 'profiles#promote_project', as: 'promote_project'
    get 'shipping', to: 'profiles#shipping', as: 'shipping'
    get 'profile_management', to: 'profiles#profile_management', as: 'profile_management'
    get 'update_cities', to: 'profiles#update_cities', as: 'update_cities'
    get 'receive_money_part2', to: 'profiles#receive_money_part2', as: 'receive_money_part2'

    get 'success', to: 'profiles#success'
    
    get  'dashboard', to: 'profiles#dashboard', as: 'dashboard'
    get  'profiles/:id', :to => 'profiles#show', :as =>  :profile
    get  'profiles/:id/edit', :to => 'profiles#edit', :as =>  :edit_profile
    post 'profiles/update', :to => 'profiles#update'
    get 'categories/:key', :to => 'categories#show', :as => :category

    resources :pledge_transactions
    resources :projects do
      resources :rewards
      resources :authors

      member do
       get 'publish'
       get 'stop'
       get 'agreement_page'
     end
      collection do
        get 'leisure'
        get 'media'
        get 'art'
        get 'crazy'
        get 'innovation'
        get 'social'
      end
    end
    namespace :api, defauts: {format: :json} do
      resources :projects, only: [:index, :show, :update] do
        resources :rewards, only: [:index, :show, :update, :create, :destroy]
      end
      resources :currencies, only: [:index]
      resources :categories, only: [:index]
      resources :cities, only: [:show, :index]
      resources :countries, only: [:index]
      resources :profiles, only: [:show, :update]
    end

  end

  devise_for :users, :controllers => {  confirmations: 'confirmations', :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController
  skip_before_filter :verify_authenticity_token  
  def index
    render json: projects
  end

  def show
    render json: project
  end

  # def create
  #   project = projects.create!(product_params)
  #   render json: project
  # end

  # def update
  #   @product = Product.find(params[:id])
  #   if @product.update_attributes(product_params)
  #     redirect_to @product
  #   else
  #     render :index
  #   end
  # end

  def update
    puts 'UPDATE START'
    params[:project] = convert_data_uri_to_upload(params[:project])
    puts 'params[:project][:image]'
    puts params[:project][:image]
    puts 'UPDATE END'

    project.update_attributes(project_params)
    render nothing: true
  end

  #def delete
  #  render json: product
  #end

  # def destroy
  #    project.destroy
  #    render nothing: true
  # end

  # def new
  #   @product = Product.new
  #   @categories = Category.all
  # end

  # def create
  #   @product = Product.new(product_params)
  #   if @product.save
  #     redirect_to products_path
  #   end
  # end

  # def edit
  #   @product = Product.find(params[:id])
  #   @categories = Category.all
  # end


  



  # def destroy
  #   Product.find(params[:id]).destroy
  #   redirect_to products_path
  # end

  private

  def project
  	@project ||= Project.find(params[:id])
  end

  def projects
  	@projects ||= Project.all  
  end

  

  def project_params
    params.require(:project).permit(
      :name, 
      :description, 
      :tweet, 
      :funding_duration_in_days, 
      :funding_goal, 
      :image, 
      :remote_image_url, 
      :video, 
      :currency_id, 
      :creator_biography, 
      :website, 
      :timeline1, 
      :timeline2, 
      :timeline3, 
      :timeline_date1, 
      :timeline_date2, 
      :timeline_date3,
      :country_id, 
      :city_id,
      :region, 
      :zip, 
      :address,
      :category_ids => []
    )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :except => [:new, :show, :index, :leisure, :media, :art, :crazy, :innovation, :social, :create]

  def new
    @project = Project.new
    @currencies = Currency.all
  end

  def create
    @project = Project.new(project_params)
    if user_signed_in?
      @project.user_id = current_user.id
      if @project.save
        category_ids = [params[:project][:category]] || []
        category_ids.each do |category_id|
          categorization = Categorization.new({:category_id => category_id, :project_id => @project.id})
          categorization.save
        end
        if !current_user.current_project_id
          current_user.current_project_id = @project.id
          current_user.save
        end
        redirect_to edit_project_url(@project.id)
      else
        render 'new'
      end
    # user are not signed in
    else
      #@project.user_id = current_user.id
      if @project.save
        category_ids = [params[:project][:category]] || []
        category_ids.each do |category_id|
          categorization = Categorization.new({:category_id => category_id, :project_id => @project.id})
          categorization.save
        end
        #Присвоить какой-то номер мол в очереди в session и в бд
        # после регистрации на edit c предзаполненными. данными
        session[:new_project_id] = @project.id
        @project.quick = true
        @project.save
        #if !current_user.current_project_id
        #  current_user.current_project_id = @project.id
        #  current_user.save
        #end
        puts "GO GO GO "
        redirect_to new_user_session_path #login/regictrstion
      else
        render 'new'
      end
    end
  end

  def show
    @project = Project.find(params[:id])
    # if @project.can_read? current_user.try(:id)
    if @project.is_published? || @project.is_owner?(current_user.try(:id))
      @project = Project.find(params[:id])

      @pledgedAmount = @project.calc_pledged
      @pledged = @project.calc_pledged_percentage @pledgedAmount
      @new_pledge = PledgeTransaction.new()
    else
      render :file => "#{Rails.root}/public/404.html", :status => :not_found
    end
  end

  def index
    @projects = Project.where(state: 'set_for_publish')
  end

  def edit
    @currencies = Currency.all
    @project = Project.find(params[:id])
    if session[:new_project_id] && (session[:new_project_id].to_i == params[:id].to_i)
      session.delete(:new_project_id)
      @project.user_id = current_user.id
      current_user.current_project_id = @project.id
      current_user.save
      @project.quick = false
      @project.save
    end

    if can?( :manage, @project) and @project.state == "created"
      @project = Project.find(params[:id])
    else
      session[:errors] = "This project can't be modified"
      redirect_to @project
    end
  end

  def update
    @project = Project.find(params[:id])
    puts 'IF START UPDATE'
    if can?( :manage, @project) and @project.state == "created"
      puts 'IF CAN'
      @project = Project.find(params[:id])
      begin
        if @project.update(project_params)
          puts 'IF UPDATE'
          # @project.update_categories params[:project][:category_ids]
          # redirect_to @project
          render 'edit'
        else
          render 'edit'
        end
      rescue ActiveRecord::StatementInvalid => ex
        session[:errors] = "Tweet is to long"
        redirect_to edit_project_path(@project)
      end
    else
      session[:errors] = "This project can't be modified"
      redirect_to @project
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  def publish
    @project = Project.find(params[:id])
    if @project.user_id == current_user.id
      if @project.set_for_publish
        flash[:notice] = "Project has transferred for a review."
        render :show
      else
        session[:errors] = @project.get_validation_errors.values.compact.join('<br/>').html_safe
        begin
          redirect_to :back
        rescue ActionController::RedirectBackError
          render :show
        end
      end
    else
      session[:errors] = "You have no rights to do that."
      begin
        redirect_to :back
      rescue ActionController::RedirectBackError
        redirect_to @project
      end
    end
  end


  def agreement_page
    @project = Project.find(params[:id])
    if @project.user_id == current_user.id
      unless @project.valid_for_publish?
        session[:errors] = @project.get_validation_errors.values.compact.join('<br/>').html_safe
        render :show
      else
        render
      end
    else
      session[:errors] = "You have no rights to do that."
      begin
        redirect_to :back
      rescue ActionController::RedirectBackError
        redirect_to @project
      end
    end
  end

  def popular
    @popular_projects = Project.where(state: 'set_for_publish')
    @popular_projects = Array.new unless @popular_projects
  end

  def successful
    @successful_projects = Project.where(state: 'set_for_publish')
    @successful_projects = Array.new unless @successful_projects
  end

  def leisure
    @category = :leisure
    @projects = Category.find_by_key(@category).projects
    render :action => 'index'
  end

  def media
    @category = :media
    @projects = Category.find_by_key(:media).projects
    render :action => 'index'
  end

  def art
    @category = :art
    @projects = Category.find_by_key(:art).projects
    puts 'TEST   '
    puts @projects
    render :action => 'index'
  end

  def crazy
    @category = :crazy
    @projects = Category.find_by_key(:crazy).projects
    render :action => 'index'
  end

  def innovation
    @category = :innovation
    @projects = Category.find_by_key(:innovation).projects
    render :action => 'index'
  end

  def social
    @category = :social
    @projects = Category.find_by_key(:social_projects).projects
    render :action => 'index'
  end

  private
    def project_params
      #console.log(params) 
      puts params.inspect
      params.require(:project).permit(
        :name, 
        :description, 
        :tweet, 
        :funding_duration_in_days, 
        :funding_goal, 
        :image, 
        :remote_image_url, 
        :video, 
        :currency_id, 
        :creator_biography, 
        :website, 
        :timeline1, 
        :timeline2, 
        :timeline3, 
        :timeline_date1, 
        :timeline_date2, 
        :timeline_date3,
        :country_id, 
        :city_id,
        :region, 
        :zip, 
        :address
      )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_banner.html.haml
- if @category.nil?
	- content_for :part1 do
		.imagewrap.shadow
			#popular_banner
			=# image_tag "banners/popular_bigbanner.png", :class => "project-banner"
			%div.button_hover
				= link_to t('learn_more').upcase, quick_start_url, :class => "button_link btn-lg"
			%h1{:class => "main_title"}
				= t('projects')
= render partial: 'projects/top_menu'

app/views/projects/_category.html.erb
<%= t(category.key).upcase %>

app/views/projects/_nav_category.html.haml
.panel.panel-default#test{:class => color}
	%a.bright{:href => category_path(title), :data => {:toggle => 'hovercollapse', :parent => '#accordion', :target => "#collapse#{key}"}}
		.panel-heading  
			.panel-title.menu_title
				%span.glyphicon.glyphicon-chevron-left.pull-left
				= t(title)
	.panel-collapse.collapse{id: "collapse#{key}"}
		.panel-body
			- subcategories.each do |subcategory|
				%a{:href => category_path(title) + "##{subcategory[:key]}"}
					= t('category.' + title + '.' + subcategory[:key])
					%ul
						- subcategory[:value].each do |subcategory2|
							%li
								%a{:href => category_path(title) + "##{subcategory2}"}
									= t('category.' + title + '.' +  subcategory2) 

app/views/projects/_new_project.html.haml
%ul.nav.new_project_link
  %li.dropdown.new_project_link
    %a{:href => "#"}
      = t('project.it_is_still_empty').upcase

app/views/projects/_projects_block.html.haml
.projects_row.projects-carousel
	%h4.project_category{ id: key }
		= caption
		- unless ['popular', 'successful'].include? key
			.link_next_to_title
				= link_to t('see_all'), category_path(key)

	- unless is_separator_hidden
		.separator_size
	- if projects.empty?
		%ul.new_project_link
			%li.new_project_link
				= render partial: 'projects/new_project'
	- else
		- projects.each do |project|
			%ul
				%li.col3-li
					= render partial: 'projects/project', locals: { project: project }
		%a.left.prev{:title => 'Previous'}
			%img{src: '/assets/prev_arrow.png'}
		%a.right.next{:title => 'Next'}
			%img{src: '/assets/next_arrow.png'}

app/views/projects/_short_form.html.haml
= form_for :project, url: projects_path, multipart: true, method: :post, html: { class: 'form-horizontal', role: 'form' } do |f|
  
  .col-sm-8.col-md-8.col-sm-offset-2.text-center.font-large.top-buffer-100
    .form-group#first-line-create-project
      %div
        I want to create a
      %div
        / Button trigger modal
        %div#hint
          %a{href: 'javascript:;', "data-target" => "#project_categories", "data-toggle" => "modal", :type => "button"}
            Category details
        %select.form-control.form-fix{:name => 'project[category]', :required => 'required', "required title" => "Please select category"}
          %option{:disabled => "disabled", :selected => "selected", :value => ""} Select category *
          - Category.all.each do |category|
            %option{:value => category.id} 
              = t(category.key)
      %div
        project
    
  .col-sm-8.col-md-8.col-sm-offset-2.text-center.font-large.big-top-buffer
    .form-group.bottom-buffer
      Name called
      %input.input-start{:name => 'project[name]', :placeholder => 'title...', :required => 'required', :pattern => ".{3,}", "required title" => "3 characters minimum"}
    .pull-right
      = f.submit t('project.start'), class: 'btn btn-start btn-success'
    .pull-left
      %select.form-control.form-fix{:name => 'project[country_id]', :required => 'required', "required title" => "Please select one country"}
        %option{:disabled => "disabled", :selected => "selected", :value => ""} Select your Country *
        - Country.all.each do |country|
          %option{:value => country.id} 
            = t(country.name)
            / %option{:value => 'Ukraine'} Ukraine
            / %option{:value => 'USA'} USA
            / %option{:value => 'Hungary'} Hungary
            / %option{:value => 'Romania'} Romania
  .col-sm-8.col-md-8.col-sm-offset-2
    %ol.country-instraction
      %li Please select the country where your project will be receiving the fund
      %li Project creation currently open to creators in Hungary and Ukraine
    .soon-open
      BC will be opening soon in:
      %br
      Poland, Croatia, France, PR China.
  .col-sm-8.col-md-8.col-sm-offset-2.big-top-buffer.bottom-buffer-100
    .col-sm-offset-3.col-sm-3.col-md-3
      = link_to t('bc_rules'), rules_path, class: 'btn btn-start btn-info btn-round'
    .col-sm-offset-1.col-sm-3.col-md-3
      = link_to t('faq_abr'), faq_path, class: 'btn btn-start btn-orange btn-round'
/ Modal
#project_categories.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-body
        = render :partial => 'home/list_subcategory'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/projects/_top_menu_element.html.haml
.panel.panel-default{:class => category + "_color"}
	%a.bright{:href => art_projects_url}
		.panel-heading  
			.panel-title.menu_title
				%span.glyphicon.glyphicon-chevron-left.pull-left
				= t(category)

app/views/projects/agreement_page.haml
Some cool agreement text
=link_to "I agree", publish_project_path(@project)
=link_to "Cancel", project_path(@project)

app/views/projects/edit.html.haml
%h1
  = t('project.edit')

- if flash[:errors]
  .error
    = flash[:errors]

/ - if !@project.published? and !@project.closed?
/   %small
/     = link_to t('project.publish'), publish_project_path(@project)

= render partial: 'projects/form'

= tinymce

app/views/projects/show.html.haml
=#<!-- TEMPORARY -->
- if flash[:notice] 
  .notice 
    = flash[:notice] 
- if flash[:errors] 
  .error 
    = flash[:errors] 
.col-sm-12.col-md-12.top-buffer-50
  =# link_to t('project.listing'), projects_path 

  - if(can?(:manage, @project))
    - if !@project.published? and !@project.closed? and !@project.on_review?
      %small
        = link_to t('project.modify'), edit_project_path(@project), :class => "btn btn-success"

      %small
        = link_to t('project.publish'), agreement_page_project_path(@project), :class => "btn btn-warning"
=#<!-- END OF TEMPORARY -->

=#<!-- MAIN PART -->
- if @project.nil?
  No project
- else 
  .col-sm-12.col-md-12.no_left_padding.big-top-buffer
    .project-title
      = @project.name
    .project-category
      %small
        = t('project.category').upcase + ':'
      - @project.categories.each do |category|
        = render :partial => 'projects/category', :locals => { category: category }
        
  .col-sm-12.col-md-12.project-content-block.top-buffer
    = render partial: 'projects/show/main'

  .col-sm-12.col-md-12.top-buffer.project-content-block
    = render partial: 'projects/show/author'
    .col-sm-12.col-md-12
      .col-sm-4.col-md-4.no_padding
        = render partial: 'social_links'
      .col-sm-1.col-md-1
        .pull-right
          %a{"data-toggle" => "tooltip", "data-placement" => "bottom", "title" => "Like", :href => "javascript:;"}
            %i.glyphicon.glyphicon-star-empty

  =#<!-- REWARDS -->
  .col-sm-12.col-md-12.top-buffer.project-content-block
    = render partial: 'projects/show/rewards'
  =#<!-- REWARDS END -->

  =#<!-- MAIN DETAILS -->
  - unless @project.description.nil?
    .col-sm-12.col-md-12.top-buffer.project-content-block
      .row.row-eq-height
        .col-sm-9.col-md-9.no_right_padding
          .col-sm-12.col-md-12.no_right_padding
            %h4.big-title-blue.text-center
              = t('main_details').upcase
              - if(can?(:manage, @project))     
                - if !@project.published? and !@project.closed? and !@project.on_review? 
                  - if user_signed_in?
                    %small
                      = link_to t('project.modify'), edit_project_path(@project)
          .col-sm-12.col-md-12
            = @project.description.html_safe

        .col-sm-3.col-md-3.right-col
          %h3
            = t('rewards').upcase
          - @project.rewards.sort { |a,b| a.per_amount <=> b.per_amount }.each do |reward|
            = render :partial => 'projects/reward', :locals => { reward: reward , hideText: ''}
        
  =#<!-- MAIN END -->

=#<!-- CREATOR DETAILS -->
.col-sm-12.col-md-12.top-buffer.project-content-block.bottom-buffer
  .col-sm-6.col-md-6
    .col-sm-6.col-md-6.author-title
      %h1
        = t('creator_details')
        - if(can?(:manage, @project))     
          - if !@project.published? and !@project.closed? and !@project.on_review? 
            - if user_signed_in?
              %small
                = link_to t('project.modify'), edit_project_path(@project)
    .col-sm-6.col-md-6.no_left_padding
      %a{:href=>'javascript:;', :class=>'thumbnail fixed-size-200'}
        = image_tag @project.author.image.url(:thumb), :class => 'fixed-size-200' if @project.author and @project.author.image?
  .col-sm-6.col-md-6.no_left_padding
    %p.content-block-lightgreen.creator-block-fix
      = t('author.name') + ':'
      = link_to(@project.author.name, profile_path(@project.author)) if @project.author 
    %p.content-block-lightgreen.creator-block-fix
      = t('author.country') + '/' + t('author.city') + ':'
      - unless @project.author.nil?
        - country = @project.author.country.nil? ? nil : @project.author.country
        - city = @project.author.city.nil? ? nil : @project.author.city
        - if((!city.nil?) && (!country.nil?))
          = country.name.to_s + ' / ' + city.name.to_s
        - elsif(!country.nil?)
          = country.name.to_s
        - elsif(!city.nil?)
          = city.name.to_s
    %p.content-block-lightgreen.creator-block-fix
      = t('project.website') + ': ' + @project.website.to_s
      %br (Optional)
    %p.content-block-lightgreen.creator-block-fix
      = t('project.location') + ':'
      = @project.country ? @project.country.name : ''
  .col-sm-12.col-md-12
    .row.row-eq-height
      .col-sm-12.col-md-12
        %h3 
          = t('creator_biography')
        .creator_bigraphy
          %p
            = @project.creator_biography
  .col-sm-4.col-md-4.no_padding.pull-right
    = render partial: 'social_links'
=#<!-- CREATOR DETAILS END -->

=#<!-- PROGRESS BAR -->
.col-sm-12.col-md-12.top-buffer.project-content-block.bottom-buffer
  .col-sm-12.col-md-12
    %h2 Project timeline
    .col-sm-4.col-md-4
      = @project.timeline1
    .col-sm-4.col-md-4
      = @project.timeline2
    .col-sm-4.col-md-4
      = @project.timeline3
    .progress.top-buffer-25
      .progress-bar.progress-bar-success{'aria-valuemax' => '33', 'aria-valuemin' => '0', 'aria-valuenow' => '40', :role => 'progressbar', :style => 'width: 35%', :title => ''}
      .progress-bar.progress-bar-info{'aria-valuemax' => '100', 'aria-valuemin' => '0', 'aria-valuenow' => '40', :role => 'progressbar', :style => 'width: 33%', :title => ''}
      .progress-bar.progress-bar-warning{'aria-valuemax' => '100', 'aria-valuemin' => '0', 'aria-valuenow' => '40', :role => 'progressbar', :style => 'width: 32%', :title => ''}
    .col-sm-4.col-md-4
      = (@project.timeline_date1.strftime("%m/%d/%Y") unless @project.timeline_date1.nil?)
    .col-sm-4.col-md-4
      = (@project.timeline_date2.strftime("%m/%d/%Y") unless @project.timeline_date2.nil?)
    .col-sm-4.col-md-4
      = (@project.timeline_date3.strftime("%m/%d/%Y") unless @project.timeline_date3.nil?)
  .col-sm-12.col-md-12
    %h4.top-buffer-30.bottom-buffe-30
      = @project.name.upcase
  .col-sm-8.col-md-8
    %h2
      = t('thank_you')
  .col-sm-4.col-md-4
    %p 
      = @project.author.name unless @project.author.name.nil?
    %p 
      = @project.address unless @project.address.nil?
    %p
      = @project.country ? @project.country.name : ''
      = @project.city ? @project.city.name : ''
      / - res = @project.country unless @project.country == ''
      / - res += ' ' + @project.city.to_s unless @project.city == ''
      / - res += ' ' + @project.region.to_s unless @project.region == ''
      / - res += ' ' + @project.zip.to_s unless @project.zip.nil?
      / = res

    / %p 4321 First Street (Optional)
    / %p Anytown, State ZIP (Optional)
=#<!-- PROGRESS BAR END -->

=#<!-- COMMENTS -->
.col-sm-12.col-md-12.top-buffer.xbig-bottom-buffer.project-content-block
  .row.row-eq-height
    .col-sm-9.col-md-9.left-col
      .form-group.padding-all-sm
        .notifications
          =link_to 'Nice', 'javascript:;', :class => 'message'
        .pull-right.blue_title  
          %a{'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Like', :href => 'javascript:;'}
            %i.glyphicon.glyphicon-star-empty
      .form-group.padding-all-sm
        .notifications
          =link_to 'Cool', 'javascript:;', :class => 'message'
        .pull-right.blue_title  
          %a{'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Like', :href => 'javascript:;'}
            %i.glyphicon.glyphicon-star-empty
      .form-group.padding-all-sm
        .notifications
          =link_to 'Awesome', 'javascript:;', :class => 'message'
        .pull-right.blue_title  
          %a{'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Like', :href => 'javascript:;'}
            %i.glyphicon.glyphicon-star-empty
      .form-group.padding-all-sm
        .notifications
          =link_to 'A popover is a light, hollow roll made from an egg batter similar to that of Yorkshire pudding, typically baked in muffin tins or dedicated popover pans, which have straight-walled sides rather than angled. ', 'javascript:;', :class => 'message'
        .pull-right.blue_title  
          %a{'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Like', :href => 'javascript:;'}
            %i.glyphicon.glyphicon-star-empty
      .form-group.padding-all-sm
        .notifications
          =link_to 'Not bad', 'javascript:;', :class => 'message'
        .pull-right.blue_title  
          %a{'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Like', :href => 'javascript:;'}
            %i.glyphicon.glyphicon-star-empty

      %br
      .blue_title 
        =link_to t('more_comments'), 'javascript:;'
    .col-sm-3.col-md-3.right-col
      %h3
        = t('rewards').upcase
      - @project.rewards.sort { |a,b| a.per_amount <=> b.per_amount }.each do |reward|
        = render :partial => 'projects/reward', :locals => { reward: reward, hideText: 'more'}
=#<!-- COMMENTS END -->
.col-sm-12.col-md-12.bottom-buffer-50
  - if(can?(:manage, @project))
    - if !@project.published? and !@project.closed? and !@project.on_review?
      %small
        = link_to t('project.modify'), edit_project_path(@project), :class => "btn btn-success"

      %small
        = link_to t('project.publish'), agreement_page_project_path(@project), :class => "btn btn-warning"



#pledgeForm.modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Pledge
      = form_for @new_pledge do |f|
        .form-group
          .modal-body
            = f.hidden_field :project_id, value: @project.id
            = f.hidden_field :currency_id, value: @project.currency_id
            -if !user_signed_in?
              .form-group.required
                = f.label :email, 'Enter your email or sign in'
                = f.text_field :email, type: 'email', class: 'form-control', required: true
            .form-group.required
              = f.hidden_field :user_id, value: current_user.id
              = f.label :amount, 'How much do you want to pledge?'
              = f.text_field  :amount, class: 'form-control', value: 10, type: 'number', required: true
          .modal-footer
            %a.btn{"data-dismiss" => "modal", :href => "#"} Close
            = f.submit 'Pledge', class: 'btn btn-primary'

:javascript
  $(document).ready(function() {
    // Configure/customize these variables.
    var showChar = 100;  // How many characters are shown by default
    var ellipsestext = "...";
    var moretext = "More";
    var lesstext = "Less";
    

    $('.more').each(function() {
        var content = $(this).html();
 
        if(content.length > showChar) {
 
            var c = content.substr(0, showChar);
            var h = content.substr(showChar, content.length - showChar);
 
            var html = c + '<span class="moreellipses">' + ellipsestext+ '&nbsp;</span><span class="morecontent"><span>' + h + '</span>&nbsp;&nbsp;<a href="" class="morelink">' + moretext + '</a></span>';
 
            $(this).html(html);
        }
 
    });
 
    $(".morelink").click(function(){
        if($(this).hasClass("less")) {
            $(this).removeClass("less");
            $(this).html(moretext);
        } else {
            $(this).addClass("less");
            $(this).html(lesstext);
        }
        $(this).parent().prev().toggle();
        $(this).prev().toggle();
        return false;
    });
  });